Create HornetQEmbeddedConfigurationFactory
Extract configuration creation to a package private
HornetQEmbeddedConfigurationFactory class so that it can be unit tested.

JMS server specific classes need to be kept out of HornetQProperties
otherwise NoClassDefFoundErrors get raised if you're missing the
-server.jar